@url = http://localhost:3000/api

# Post Endpoints


# Obtener todos los posts
GET {{url}}/post

###

# Obtener un post por ID (reemplaza :postId con un ID válido)
GET {{url}}/post/:postId

###

# Crear un nuevo post
POST {{url}}/post
Content-Type: application/json

{
    "titulo": "Nuevo Post de Ejemplo",
    "descripcion": "Descripción del post de ejemplo",
    "categoria": "Categoría de ejemplo",
    "autor_id": 1  # Reemplazar con el ID de un autor existente
}


###
# Obtener todos los posts de un autor específico (reemplaza :autorId con un ID válido)
GET {{url}}/post/autor/:autorId
